### ISSUE TITLE
Proper licensing for including archieml-js (APLv2)?

### ISSUE THREAD

**Issue by noamross** [ropensci/rchie#1]
archieml-js is Apache 2.0 licensed.  I'm not sure what I need to to to include this (unmodified) code in my package.  Can I use MIT for this package?  I know I can use GPL.

**Comment by abstrctn** [comment]
Hi Noam - this is awesome!

We're still working on dual licensing under MIT, but including the LICENSE file in the same directory as archieml.js (as you're already doing) is enough as it is.

**Comment by noamross** [comment]
Great, thanks!
