### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by maelle** [ropensci/rchie#10]
@noamross Has development of this package been suspended? Should it get a suspended or abandoned status badge and then be archived (reversible decision) like [a few other repos](https://github.com/ropensci?utf8=%E2%9C%93&q=&type=archived&language=)?

**Comment by noamross** [comment]
Yeah, let's go with suspended.  It was a minimal usable version that hasn't kept up with changes to the underlying JS, and was added pre-onboarding.

**Comment by maelle** [comment]
Are you fine with my archiving it? I'd

* close all issues

* add a stop sign and SUSPENDED to the repo description (bc otherwise the archived status isn't very clear in search results)

* add the badge

* and archive the repo
